Use principals in var _additional_system_admins
confluentinc/cp-ansible pull request #1213
Opened 2022-10-27 10:46 UTC by utkarsh5474

# Description

https://github.com/confluentinc/cp-ansible/issues/726
Additional RBAC systemadmins rolebindings were hardcoded to User:xyz principal. This PR adds Group:abc too

This is a variable change. So, customer facing doc change required here - https://docs.confluent.io/ansible/current/ansible-authorize.html#optional-settings-for-rbac

Alt rejected option - To create a separate variable and task for assigning groups. And let the current var rbac_component_additional_system_admins be used for Users

Fixes # ([GH-726](https://confluentinc.atlassian.net/browse/ANSIENG-1852))

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# How Has This Been Tested?

Has been tested on 7.3.x branch - https://jenkins.confluent.io/job/cp-ansible-on-demand/647/ 
The failing molecule scenario has been fixed

**Test Configuration**:

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation -> Pending
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] Any variable changes have been validated to be backwards compatible

2022-10-27 11:23 UTC, nsharma-git requested changes
This would break the upgrade path. We should parse the item and add the "User" principal if not available in the inventory file.

2022-10-27 11:26 UTC, utkarsh5474 commented
So, we'll default to User if there's no User: or Group: in the principal? 
That'll be an inconsistent variable. 
I was thinking to take the alt option - 
Separate vars/task for rolebindings on groups. WDYT?

2022-10-28 10:26 UTC, utkarsh5474 commented
Addressed the comments.
Latest test run (all passing)- https://jenkins.confluent.io/job/cp-ansible-on-demand/654/
@nsharma-git , PTAL

2022-11-02 06:53 UTC, nsharma-git approved these changes

2022-11-02 06:55 UTC, merged