Bump CLI to v3.2.0
confluentinc/cp-ansible pull request #1345
Opened 2023-02-20 06:19 UTC by wadhwa1

# Description

Bumping up pinned cli version for cp 7.4 from 2.28.1 to 3.2.0
Reference thread - https://confluent.slack.com/archives/C010Y0EP5MZ/p1675164016491029
Another related PR - https://github.com/confluentinc/packaging/pull/1049

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

**Test Configuration**:

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] Any variable changes have been validated to be backwards compatible

2023-02-20 06:23 UTC, utkarsh5474 approved these changes

2023-02-20 07:33 UTC, nsharma-git approved these changes

2023-02-22 21:26 UTC, brianstrauch requested changes
Please bump to v3.2.1!

2023-02-22 21:26 UTC, brianstrauch commented on docs/VARIABLES.md
> +Default:  3.2.0
```suggestion
Default:  3.2.1
```

2023-02-22 21:26 UTC, brianstrauch commented on roles/variables/defaults/main.yml
> +confluent_cli_version: 3.2.0
```suggestion
confluent_cli_version: 3.2.1
```

2023-02-23 05:54 UTC, brianstrauch approved these changes

2023-02-23 07:25 UTC, wadhwa1 commented
> Please bump to v3.2.1!

Thanks Brian for the review! :) 
currently, tests are failing for -
```
11:00:58  TASK [confluent.platform.common : Expand remote Confluent CLI archive] *********
11:01:03  fatal: [zookeeper32]: FAILED! => {"changed": false, "msg": "Failure downloading https://s3-us-west-2.amazonaws.com/confluent.cloud/confluent-cli/archives/3.2.1/confluent_v3.2.1_linux_amd64.tar.gz, HTTP Error 404: Not Found"}
```
I believe, once this PR https://github.com/confluentinc/packaging/pull/1049 is merged, we'll have this archive available in s3 bucket ??

2023-02-23 07:27 UTC, brianstrauch commented
@wadhwa1 Please remove the leading "v" in the version number! `confluent_v3.2.1_linux_amd64.tar.gz` should become `confluent_3.2.1_linux_amd64.tar.gz`.

2023-02-23 09:25 UTC, wadhwa1 commented
> @wadhwa1 Please remove the leading "v" in the version number! `confluent_v3.2.1_linux_amd64.tar.gz` should become `confluent_3.2.1_linux_amd64.tar.gz`.

ahh okay, that's little strange.. because all the while we have been prepending 'v' in front of cli version (in cp-ansible code)
```
### A path reference to a local archive file or URL. By default this is the URL from Confluent CLI repository.
confluent_cli_archive_file_source: "{{confluent_cli_repository_baseurl}}/confluent-cli/archives/{{confluent_cli_version}}/{{confluent_cli_binary}}_{{(confluent_cli_version == 'latest') | ternary('', 'v')}}{{confluent_cli_version}}_{{ansible_system|lower}}_{{confluent_cli_goarch[ansible_architecture]}}.tar.gz”
```
Has this changed recently and is this the new convention ?

2023-02-23 18:24 UTC, brianstrauch commented
@wadhwa1 Yes, all versions of the CLI 3.x and above no longer have the "v" in the archive name. It's an industry standard and what customers expect!

2023-02-23 18:29 UTC, wadhwa1 commented
> @wadhwa1 Yes, all versions of the CLI 3.x and above no longer have the "v" in the archive name. It's an industry standard and what customers expect!

perfect, thanks for clarifying @brianstrauch ! 👍

2023-02-24 06:27 UTC, merged