61 remove jolokia health check dependency
confluentinc/cp-ansible pull request #480
Opened 2020-11-10 22:43 UTC by domenicbove

# Description

Do kafka health checks without any reliance on jolokia agent. There is high demand to remove jolokia agent

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

All scenarios must still work

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] Any variable changes have been validated to be backwards compatible

2020-11-10 22:44 UTC, domenicbove commented on roles/confluent.kafka_broker/tasks/health_check.yml
>    delay: 5
need the ignore-errors true so that failure handling tasks still run

2020-11-12 19:20 UTC, domenicbove commented on roles/confluent.kafka_broker/tasks/health_check.yml
> +- name: Get Topics with UnderReplicatedPartitions
consider idempotency!

2020-11-12 19:21 UTC, domenicbove commented on roles/confluent.kafka_broker/tasks/ordered_restart.yml
> +- name: Get Controller Broker ID
consider idempotency

2020-11-12 19:23 UTC, domenicbove commented on roles/confluent.kafka_broker/tasks/ordered_restart.yml
> +  shell: |
missing digest auth mechanism

2020-11-12 19:40 UTC, domenicbove commented on roles/confluent.kafka_broker/tasks/ordered_restart.yml
> +  shell: |
also check the scram creation task

2020-11-16 18:02 UTC, domenicbove commented on roles/confluent.kafka_broker/tasks/ordered_restart.yml
> +  shell: |
seems this command is running without the kafka_opts env var

2020-11-16 19:20 UTC, domenicbove commented on roles/confluent.kafka_broker/tasks/ordered_restart.yml
> +  shell: |
tested on zk w kerberos and digest auth

2020-11-18 00:16 UTC, domenicbove commented on roles/confluent.kafka_broker/tasks/ordered_restart.yml
> +  register: controller_query
also need to move this step into upgrade script

2020-11-23 11:46 UTC, JumaX commented on tasks/create_ordered_kafka_groups.yml
> +- name: Search for Zookeeper SSL Property
Could we not use line in file module here as opposed to using a shell command?

2020-11-23 11:47 UTC, JumaX commented on tasks/create_ordered_kafka_groups.yml
> +- name: Search for Kafka Broker ID
Would line in file module work here?

2020-11-23 11:51 UTC, JumaX requested changes
@domenicbove great job.  Just a few minor questions.

2020-11-23 16:54 UTC, domenicbove commented on tasks/create_ordered_kafka_groups.yml
> +- name: Search for Zookeeper SSL Property
Ya looks like there is a sorta complicated way to get lineinefile to work: https://stackoverflow.com/questions/30786263/only-check-whether-a-line-present-in-a-file-ansible

This way is still idempotent. It will never show changed, and will run if ansible is in check mode.

I think whats in the stack overflow is essentially the equivalent of whats here. Do you feel changing to that is a good idea?

2020-11-23 19:12 UTC, domenicbove commented on tasks/create_ordered_kafka_groups.yml
> +- name: Search for Zookeeper SSL Property
went with the slurp module because i needed additional logic in the second grep command, take a look!

2020-11-24 11:12 UTC, JumaX approved these changes
@domenicbove Amazing job!  The slurping of the configs is really cool.

2020-11-24 15:25 UTC, merged