Health Check Customization Variables
confluentinc/cp-ansible pull request #488
Opened 2020-11-20 17:39 UTC by domenicbove

# Description

Adds variables to disable component health checks
Adds user/pass variables for the health checks

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

All scenarios should continue to function
TODO add basic auth scenario that proves the effectiveness

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] Any variable changes have been validated to be backwards compatible

2020-11-20 17:40 UTC, domenicbove commented on roles/confluent.variables/defaults/main.yml
> +### Password for authenticated Control Center Health Check. Set if using customized security like Basic Auth
run docs.py

2020-11-24 11:29 UTC, JumaX commented on VARIABLES.md
> +User for authenticated MDS Health Check. Only relevant if rbac_enabled: true. Likely leave as is
```suggestion
User for authenticated MDS Health Check. Only relevant if rbac_enabled: true.
```

2020-11-24 11:30 UTC, JumaX commented on VARIABLES.md
> +Password for authenticated MDS Health Check. Only relevant if rbac_enabled: true. Likely leave as is
```suggestion
Password for authenticated MDS Health Check. Only relevant if rbac_enabled: true. 
```

2020-11-24 11:30 UTC, JumaX commented on VARIABLES.md
> +User for authenticated Kafka Admin API Health Check. Set if using customized security like Basic Auth
```suggestion
User for authenticated Kafka Admin API Health Check. Set if using customized security like Basic Authd.
```

2020-11-24 11:30 UTC, JumaX commented on VARIABLES.md
> +Password for authenticated Kafka Admin API Health Check. Set if using customized security like Basic Auth
```suggestion
Password for authenticated Kafka Admin API Health Check. Set if using customized security like Basic Auth.
```

2020-11-24 11:31 UTC, JumaX commented on VARIABLES.md
> +User for authenticated Schema Registry Health Check. Set if using customized security like Basic Auth
```suggestion
User for authenticated Schema Registry Health Check. Set if using customized security like Basic Auth.
```

2020-11-24 11:31 UTC, JumaX commented on VARIABLES.md
> +Password for authenticated Schema Registry Health Check. Set if using customized security like Basic Auth
```suggestion
Password for authenticated Schema Registry Health Check. Set if using customized security like Basic Auth.
```

2020-11-24 11:31 UTC, JumaX commented on VARIABLES.md
> +User for authenticated Connect Health Check. Set if using customized security like Basic Auth
```suggestion
User for authenticated Connect Health Check. Set if using customized security like Basic Auth.
```

2020-11-24 11:31 UTC, JumaX commented on VARIABLES.md
> +Password for authenticated Connect Health Check. Set if using customized security like Basic Auth
```suggestion
Password for authenticated Connect Health Check. Set if using customized security like Basic Auth.
```

2020-11-24 11:31 UTC, JumaX commented on VARIABLES.md
> +User for authenticated ksqlDB Health Check. Set if using customized security like Basic Auth
```suggestion
User for authenticated ksqlDB Health Check. Set if using customized security like Basic Auth.
```

2020-11-24 11:32 UTC, JumaX commented on VARIABLES.md
> +Password for authenticated Control Center Health Check. Set if using customized security like Basic Auth
```suggestion
Password for authenticated Control Center Health Check. Set if using customized security like Basic Auth.
```

2020-11-24 11:32 UTC, JumaX commented on VARIABLES.md
> +User for authenticated Control Center Health Check. Set if using customized security like Basic Auth
```suggestion
User for authenticated Control Center Health Check. Set if using customized security like Basic Auth.
```

2020-11-24 11:32 UTC, JumaX commented on VARIABLES.md
> +Password for authenticated Rest Proxy Health Check. Set if using customized security like Basic Auth
```suggestion
Password for authenticated Rest Proxy Health Check. Set if using customized security like Basic Auth.
```

2020-11-24 11:32 UTC, JumaX commented on VARIABLES.md
> +User for authenticated Rest Proxy Health Check. Set if using customized security like Basic Auth
```suggestion
User for authenticated Rest Proxy Health Check. Set if using customized security like Basic Auth.
```

2020-11-24 11:32 UTC, JumaX commented on VARIABLES.md
> +Password for authenticated ksqlDB Health Check. Set if using customized security like Basic Auth
```suggestion
Password for authenticated ksqlDB Health Check. Set if using customized security like Basic Auth.
```

2020-11-24 11:46 UTC, JumaX commented on roles/confluent.variables/defaults/main.yml
> +### User for authenticated MDS Health Check. Only relevant if rbac_enabled: true. Likely leave as is
```suggestion
### User for authenticated MDS Health Check. Only relevant if rbac_enabled: true. Likely leave as is.
```

2020-11-24 11:47 UTC, JumaX commented on roles/confluent.variables/defaults/main.yml
> +### Password for authenticated MDS Health Check. Only relevant if rbac_enabled: true. Likely leave as is
```suggestion
### Password for authenticated MDS Health Check. Only relevant if rbac_enabled: true.

2020-11-24 11:47 UTC, JumaX commented on roles/confluent.variables/defaults/main.yml
> +### User for authenticated Kafka Admin API Health Check. Set if using customized security like Basic Auth
```suggestion
### User for authenticated Kafka Admin API Health Check. Set if using customized security like Basic Auth.
```

2020-11-24 11:47 UTC, JumaX commented on roles/confluent.variables/defaults/main.yml
> +### Password for authenticated Kafka Admin API Health Check. Set if using customized security like Basic Auth
```suggestion
### Password for authenticated Kafka Admin API Health Check. Set if using customized security like Basic Auth.
```

2020-11-24 11:47 UTC, JumaX commented on roles/confluent.variables/defaults/main.yml
> +### User for authenticated Schema Registry Health Check. Set if using customized security like Basic Auth
```suggestion
### User for authenticated Schema Registry Health Check. Set if using customized security like Basic Auth.
```

2020-11-24 11:48 UTC, JumaX commented on roles/confluent.variables/defaults/main.yml
> +### Password for authenticated Schema Registry Health Check. Set if using customized security like Basic Auth
```suggestion
### Password for authenticated Schema Registry Health Check. Set if using customized security like Basic Auth.
```

2020-11-24 11:48 UTC, JumaX commented on roles/confluent.variables/defaults/main.yml
> +### User for authenticated Connect Health Check. Set if using customized security like Basic Auth
```suggestion
### User for authenticated Connect Health Check. Set if using customized security like Basic Auth.
```

2020-11-24 11:48 UTC, JumaX commented on roles/confluent.variables/defaults/main.yml
> +### Password for authenticated Connect Health Check. Set if using customized security like Basic Auth
```suggestion
### Password for authenticated Connect Health Check. Set if using customized security like Basic Auth.
```

2020-11-24 11:48 UTC, JumaX commented on roles/confluent.variables/defaults/main.yml
> +### User for authenticated ksqlDB Health Check. Set if using customized security like Basic Auth
```suggestion
### User for authenticated ksqlDB Health Check. Set if using customized security like Basic Auth.
```

2020-11-24 11:48 UTC, JumaX commented on roles/confluent.variables/defaults/main.yml
> +### Password for authenticated ksqlDB Health Check. Set if using customized security like Basic Auth
```suggestion
### Password for authenticated ksqlDB Health Check. Set if using customized security like Basic Auth.
```

2020-11-24 11:49 UTC, JumaX commented on roles/confluent.variables/defaults/main.yml
> +### User for authenticated Rest Proxy Health Check. Set if using customized security like Basic Auth
```suggestion
### User for authenticated Rest Proxy Health Check. Set if using customized security like Basic Auth.
```

2020-11-24 11:49 UTC, JumaX commented on roles/confluent.variables/defaults/main.yml
> +### Password for authenticated Rest Proxy Health Check. Set if using customized security like Basic Auth
```suggestion
### Password for authenticated Rest Proxy Health Check. Set if using customized security like Basic Auth.
```

2020-11-24 11:49 UTC, JumaX commented on roles/confluent.variables/defaults/main.yml
> +### User for authenticated Control Center Health Check. Set if using customized security like Basic Auth
```suggestion
### User for authenticated Control Center Health Check. Set if using customized security like Basic Auth.
```

2020-11-24 11:49 UTC, JumaX commented on roles/confluent.variables/defaults/main.yml
> +### Password for authenticated Control Center Health Check. Set if using customized security like Basic Auth
```suggestion
### Password for authenticated Control Center Health Check. Set if using customized security like Basic Auth.
```

2020-11-24 11:50 UTC, JumaX requested changes
@domenicbove just some minor changes.  Great work here!

2020-11-24 15:31 UTC, JumaX approved these changes
LGTM.

2020-11-24 15:51 UTC, merged