Create Jolokia and Prom JMX exporter directories based on jar path
confluentinc/cp-ansible pull request #501
Opened 2020-12-10 13:19 UTC by jeqo

# Description

Directories to place JARs are being created with hard-coded paths. Instead jar_paths can be used to create a proper directory if variables change.

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] Any variable changes have been validated to be backwards compatible

2020-12-10 14:07 UTC, domenicbove commented on roles/confluent.common/tasks/main.yml
> +    path: "{{ jolokia_jar_path | name }}"
```suggestion
    path: "{{ jolokia_jar_path | dirname }}"
```

2020-12-10 14:07 UTC, domenicbove approved these changes
Great catch! one minor typo

2020-12-10 15:08 UTC, JumaX approved these changes
LGTM.

2020-12-10 15:11 UTC, JumaX requested changes
@jeqo Can you rebase this to 5.5.x, as we should fix it there as well.

2020-12-11 13:13 UTC, JumaX approved these changes
LGTM!

2020-12-11 13:13 UTC, merged