Allow for customization of the Unit section of systemd service files
confluentinc/cp-ansible pull request #525
Opened 2021-01-15 21:31 UTC by domenicbove

# Description

Introduces new variables for each component to customize systemd unit section. Feature not used on most installs.
Improved docs around other override.conf dictionaries

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

added test to plain-rhel

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] Any variable changes have been validated to be backwards compatible

2021-01-18 09:19 UTC, JumaX commented
@domenicbove I am not sure we should actually be allowing the overrides, as discussed this seems like a problem in packaging itself, and should be cleared with the packaging team.

2021-01-19 01:08 UTC, domenicbove commented
@JumaX This PR does not take a stance on if there are issues w the packages or not, it just allows for more customizations if you'd like them. In my molecule tests, I tested out customizing the Description. This PR does not change the default behavior of the install

2021-01-19 10:45 UTC, JumaX commented
@domenicbove Apologies, I don't think I am articulating myself well here.  Essentially I am saying that the fundamental problem is with the packaging and thus needs to get fixed there.  We can implement the above, but it's effectively "wall papering" over a deeper issue.  Do we have a bug filed against fixing the packaging?

2021-01-19 17:01 UTC, domenicbove commented
@JumaX I do not actually think there is anything wrong w the packaging. I view this more of a we allow for customizing most things why not allow this customization as well.

For example, these are the lines in your systemd file in the replicator pr:
```
[Unit]
Description= Kafka Connect Replicator
Documentation=http://docs.confluent.io/
After=network.target confluent-server.target
```

This allows for the customization of **any** of those lines. Like what if someone writes their own docs, or wanted to point to the actual replicator docs.

2021-01-20 18:26 UTC, andrewegel commented
>  Essentially I am saying that the fundamental problem is with the packaging and thus needs to get fixed there

SystemD Unit files that ship with OS packages are marked as configuration files, as in they're intended to be edited & customized to the environment they're installed/running on. "Out of the box" the Unit files should take care of launching the service within systemd. 

As to removing `confluent-zookeeper.target` from the `After` line in CE/CCS kafka: This is more up to the Kafka Product team on how they want to present the "Confluent Platform Experience" - If "out of the box" they want everything running on the same host (like in a Demo), then `After=confluent-zookeeper.target` targets make sense, but when it comes to an actual production deployment with non-coolocated services, these values would need to be overridden for it to make sense, which is what tools like Puppet, Chef & Ansible are for. Finding the balance between that "out of the box experience" vs production deployments is not something I'm in a position to make a call on.

2021-01-20 19:26 UTC, shawn35gh commented
LGTM

2021-01-25 09:24 UTC, JumaX commented
@andrewegel Thanks for the clarification, this is super helpful in understanding the different config models.

2021-01-25 09:27 UTC, JumaX commented on roles/confluent.control_center/defaults/main.yml
> +# For following dictionaries, Key/Value Pairs of with empty values will not be written into override.conf
```suggestion
# For following dictionaries, Key/Value Pairs with empty values will not be written into override.conf
```

2021-01-25 09:31 UTC, JumaX commented on roles/confluent.kafka_connect/defaults/main.yml
> +# For following dictionaries, Key/Value Pairs of with empty values will not be written into override.conf
```suggestion
# For following dictionaries, Key/Value Pairs with empty values will not be written into override.conf
```

2021-01-25 09:33 UTC, JumaX commented on roles/confluent.kafka_rest/defaults/main.yml
> +# For following dictionaries, Key/Value Pairs of with empty values will not be written into override.conf
```suggestion
# For following dictionaries, Key/Value Pairs with empty values will not be written into override.conf
```

2021-01-25 09:33 UTC, JumaX commented on roles/confluent.ksql/defaults/main.yml
> +# For following dictionaries, Key/Value Pairs of with empty values will not be written into override.conf
```suggestion
# For following dictionaries, Key/Value Pairs with empty values will not be written into override.conf
```

2021-01-25 09:34 UTC, JumaX commented on roles/confluent.schema_registry/defaults/main.yml
> +# For following dictionaries, Key/Value Pairs of with empty values will not be written into override.conf
```suggestion
# For following dictionaries, Key/Value Pairs with empty values will not be written into override.conf
```

2021-01-25 09:37 UTC, JumaX commented on roles/confluent.zookeeper/defaults/main.yml
> +# For following dictionaries, Key/Value Pairs of with empty values will not be written into override.conf
```suggestion
# For following dictionaries, Key/Value Pairs with empty values will not be written into override.conf
```

2021-01-25 09:37 UTC, JumaX requested changes
A few minor comment changes, otherwise looks good.

2021-01-25 15:02 UTC, domenicbove commented on roles/confluent.kafka_broker/defaults/main.yml
> +# For following dictionaries, Key/Value Pairs of with empty values will not be written into override.conf
```suggestion
# For following dictionaries, Key/Value Pairs with empty values will not be written into override.conf
```

2021-01-25 15:19 UTC, JumaX approved these changes
LGTM.

2021-01-25 15:27 UTC, shawn35gh approved these changes

2021-01-25 17:31 UTC, rohit2b approved these changes
LGTM!

2021-01-25 17:43 UTC, merged