Fix molecule tests for scenario 'mtls-customcerts-rhel'
confluentinc/cp-ansible pull request #847
Opened 2021-12-07 08:34 UTC by utkarsh5474

# Description

Molecule tests for the scenario 'mtls-customcerts-rhel' were failing on task:
`TASK [confluent.zookeeper : Install the Zookeeper Packages]` with error as `Error: confluent-server conflicts with confluent-kafka-2.12-5.5.7-1.noarch`
Enabling default value of 'confluent_server_enabled' (which is true) resolved the issue. 

Fixes # ([As part of 5.5.x release readiness](https://confluentinc.atlassian.net/browse/ANSIENG-963?atlOrigin=eyJpIjoiYjZhOTEyNGUwYzgxNGRhMjllNGVkZmMzNWRlMDdiNWYiLCJwIjoiaiJ9))

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

`molecule --debug test -s mtls-customcerts-rhel` gives all pass/success.

**Test Configuration**: molecule run for scenario mtls-customcerts-rhel on 5.5.x

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] Any variable changes have been validated to be backwards compatible

2021-12-07 16:44 UTC, JumaX requested changes
I don't think this is the correct solution here, as we have a few scenarios where we have deliberately set confluent_server_enabled to false as to test with Confluent Open Source version.

I would investigate the error further for resolution.

2021-12-07 17:36 UTC, utkarsh5474 commented
Yeah @JumaX 
I thought so too. 
But then, I tried to see the 6.0.x branch for this same scenario and file. The same fix came up sometime back. 
So, I think we'll need to evaluate the fix on 6.0.x too.

2021-12-09 13:45 UTC, utkarsh5474 commented
New changes: 
Undo previous change. Disable dockerfile use.

The custom Dockerfile.j2 installs confluent server on all images.
With `confluent_server_enabled = false`, the confluent-kafka-2.12 package is installed on all docker images. 
This is what is leading to the conflict.

`molecule --debug test -s mtls-customcerts-rhel` with these new changes gives all pass/success.

2021-12-09 13:53 UTC, JumaX commented on roles/confluent.test/molecule/mtls-customcerts-rhel/molecule.yml
> +    # dockerfile: ../Dockerfile.j2
Please remove this line completely, it's not necessary if we don't use the docker file.

2021-12-09 13:54 UTC, JumaX requested changes
Minor change, but great work in getting to the root cause!

2021-12-09 13:54 UTC, JumaX commented on roles/confluent.test/molecule/mtls-customcerts-rhel/molecule.yml
> +    # dockerfile: ../Dockerfile.j2
Please remove this line completely, it's not necessary if we don't use the docker file.

2021-12-09 13:54 UTC, JumaX commented on roles/confluent.test/molecule/mtls-customcerts-rhel/molecule.yml
> +    # dockerfile: ../Dockerfile.j2
Please remove this line completely, it's not necessary if we don't use the docker file.

2021-12-09 13:54 UTC, JumaX commented on roles/confluent.test/molecule/mtls-customcerts-rhel/molecule.yml
> +    # dockerfile: ../Dockerfile.j2
Please remove this line completely, it's not necessary if we don't use the docker file.

2021-12-09 13:54 UTC, JumaX commented on roles/confluent.test/molecule/mtls-customcerts-rhel/molecule.yml
> +    # dockerfile: ../Dockerfile.j2
Please remove this line completely, it's not necessary if we don't use the docker file.

2021-12-09 13:54 UTC, JumaX commented on roles/confluent.test/molecule/mtls-customcerts-rhel/molecule.yml
> +    # dockerfile: ../Dockerfile.j2
Please remove this line completely, it's not necessary if we don't use the docker file.

2021-12-09 13:54 UTC, JumaX commented on roles/confluent.test/molecule/mtls-customcerts-rhel/molecule.yml
> +    # dockerfile: ../Dockerfile.j2
Please remove this line completely, it's not necessary if we don't use the docker file.

2021-12-09 13:54 UTC, JumaX commented on roles/confluent.test/molecule/mtls-customcerts-rhel/molecule.yml
> +    # dockerfile: ../Dockerfile.j2
Please remove this line completely, it's not necessary if we don't use the docker file.

2021-12-09 13:54 UTC, JumaX commented on roles/confluent.test/molecule/mtls-customcerts-rhel/molecule.yml
> +    # dockerfile: ../Dockerfile.j2
Please remove this line completely, it's not necessary if we don't use the docker file.

2021-12-14 10:09 UTC, JumaX approved these changes
LGTM.

2021-12-14 17:31 UTC, merged