Fix formatting issue
confluentinc/cp-ansible pull request #875
Opened 2021-12-28 20:19 UTC by nsharma-git

# Description

This PR fixes a few formatting issue for rbac_replicator task

Fixes # (ANSIENG-998)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

```
TASK [confluent.kafka_connect_replicator : Configure RBAC on Replicator configuration] ***
included: /Work/repos/ansible_collections/confluent/platform/roles/confluent.kafka_connect_replicator/tasks/rbac_replicator.yml for kafka-connect-replicator1

TASK [confluent.kafka_connect_replicator : Create SSL Certificate Directory] ***
--- before
+++ after
@@ -1,4 +1,4 @@
 {
     "path": "/var/ssl/private/kafka_connect_replicator",
-    "state": "absent"
+    "state": "directory"
 }

changed: [kafka-connect-replicator1]

TASK [confluent.kafka_connect_replicator : Copy in MDS Public Pem File] ********
changed: [kafka-connect-replicator1]

TASK [confluent.kafka_connect_replicator : Grant Confluent Replicator User SystemAdmin on Kafka cluster] ***
skipping: [kafka-connect-replicator1]

TASK [confluent.kafka_connect_replicator : Grant Confluent Replicator User SystemAdmin on Replicator Cluster] ***
skipping: [kafka-connect-replicator1]

TASK [confluent.kafka_connect_replicator : Grant Confluent Replicator User ResourceOwner on Connect Topics] ***
skipping: [kafka-connect-replicator1]

TASK [confluent.kafka_connect_replicator : Grant Confluent Replicator User Developer Read on Command Topic] ***
skipping: [kafka-connect-replicator1]

TASK [confluent.kafka_connect_replicator : Grant Confluent Replicator User Developer Write on Command Topic] ***
skipping: [kafka-connect-replicator1]

TASK [confluent.kafka_connect_replicator : Grant Confluent Replicator User Developer Manage on Command Topic] ***
skipping: [kafka-connect-replicator1]

TASK [confluent.kafka_connect_replicator : Grant Confluent Replicator User SystemAdmin on Kafka cluster] ***
ok: [kafka-connect-replicator1]

TASK [confluent.kafka_connect_replicator : Grant Confluent Replicator User SystemAdmin on Replicator Cluster] ***
ok: [kafka-connect-replicator1]

TASK [confluent.kafka_connect_replicator : Grant Confluent Replicator User ResourceOwner on Connect Topics] ***
ok: [kafka-connect-replicator1]

TASK [confluent.kafka_connect_replicator : Grant Confluent Replicator User Developer Read on Command Topic] ***
ok: [kafka-connect-replicator1]

TASK [confluent.kafka_connect_replicator : Grant Confluent Replicator User Developer Write on Command Topic] ***
ok: [kafka-connect-replicator1]

TASK [confluent.kafka_connect_replicator : Grant Confluent Replicator User Developer Manage on Command Topic] ***
ok: [kafka-connect-replicator1]

TASK [confluent.kafka_connect_replicator : Grant Confluent Replicator User Security Admin on Destination cluster] ***
ok: [kafka-connect-replicator1]

```

**Test Configuration**:
` molecule --debug converge -s rbac-kafka-connect-replicator-kerberos-mtls-custom-rhel`

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] Any variable changes have been validated to be backwards compatible

2021-12-29 04:07 UTC, utkarsh5474 reviewed
Hey @nsharma-git 
There a couple of more files where there are formatting issues of extra `}}` like this one `"{{kafka_connect_replicator_kafka_cluster_id}}"}}` 
The files I could find - 
```
roles/confluent.kafka_connect/tasks/rbac.yml
roles/confluent.kafka_connect_replicator/tasks/rbac_replicator_consumer.yml
roles/confluent.kafka_connect_replicator/tasks/rbac_replicator_producer.yml
```
Should we add this in the current PR

2021-12-29 05:47 UTC, nsharma-git commented
> Hey @nsharma-git There a couple of more files where there are formatting issues of extra `}}` like this one `"{{kafka_connect_replicator_kafka_cluster_id}}"}}` The files I could find -
> 
> ```
> roles/confluent.kafka_connect/tasks/rbac.yml
> roles/confluent.kafka_connect_replicator/tasks/rbac_replicator_consumer.yml
> roles/confluent.kafka_connect_replicator/tasks/rbac_replicator_producer.yml
> ```
> 
> Should we change these in the current PR?

Thanks @utkarsh5474.
 I think it make sense to have these changes in this PR itself. I'll update this PR shortly.

2021-12-30 10:45 UTC, utkarsh5474 requested changes
I believe, most of the changes around double parenthesis will need to be changed as per this - https://docs.confluent.io/platform/current/security/rbac/mds-api.html#post--security-1.0-principals-principal-roles-roleName-bindings

2022-01-03 05:15 UTC, nsharma-git commented
> I believe, most of the changes around double parenthesis will need to be changed as per this - https://docs.confluent.io/platform/current/security/rbac/mds-api.html#post--security-1.0-principals-principal-roles-roleName-bindings

Sorry, didn't get it. What changes you are proposing?

2022-01-03 14:24 UTC, nsharma-git commented
> I believe, most of the changes around double parenthesis will need to be changed as per this - https://docs.confluent.io/platform/current/security/rbac/mds-api.html#post--security-1.0-principals-principal-roles-roleName-bindings

Good catch @utkarsh5474 
Can you please have a look on the updated PR

2022-01-04 06:00 UTC, nsharma-git commented on roles/confluent.kafka_connect_replicator/tasks/rbac_replicator_producer.yml
> +            "kafka-cluster":"{{kafka_connect_replicator_producer_kafka_cluster_id}}",
Done!

2022-01-04 06:32 UTC, utkarsh5474 approved these changes
Thanks!

2022-01-04 06:56 UTC, merged