Remove conflicting properties
confluentinc/cp-ansible pull request #947
Opened 2022-03-02 20:11 UTC by nsharma-git

# Description

We have variable `kafka_broker` defined in vars as well as in default. Since vars has higher precedence then default, the resultant dictionary doesn't have any `properties` key. This causes the play to fail with error 
```
fatal: [zookeeper1]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: {{ zookeeper_combined_properties | combine(zookeeper_custom_properties) }}: {{ zookeeper.properties }}: 'dict object' has no attribute 'properties'\n
```

Fixes #[RCCA-6061](https://confluentinc.atlassian.net/browse/RCCA-6061)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

` ansible-playbook -i ../../hosts.ini ../../all.yml `
Since the user was trying out with ini file, we have verified with an ini file

**Test Configuration**:
Local environment

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] Any variable changes have been validated to be backwards compatible

2022-03-03 14:24 UTC, JumaX commented
Also recommend updating one of the molecule scenarios to make sure custom properties for each component are tested.

2022-03-03 14:24 UTC, JumaX requested changes
See comments on testing recommendations.

2022-03-08 08:27 UTC, nsharma-git commented
> @nsharma-git Recommend you test this with one of our molecule scenarios using custom properties to validate nothing else has been broken by this change.

We have verified `plain-rhel` which has  **zookeeper_custom_properties** along with `rbac-kafka-connect-replicator-kerberos-mtls-custom-rhel` which has **kafka_broker_custom_properties**, **kafka_connect_replicator_consumer_custom_properties**  and **kafka_connect_replicator_producer_custom_properties**
Jenkins url - https://jenkins.confluent.io/job/cp-ansible-on-demand/109

2022-03-10 06:55 UTC, nsharma-git commented on roles/variables/vars/main.yml
> +  log_path: "{{zookeeper_default_log_dir}}"
Thanks for pointing this out. Updated all log properties.

2022-03-14 10:58 UTC, nsharma-git commented
Since we are in code freeze for 7.1.x moving this to master branch. @domenicbove, @JumaX Please have a look

2022-03-15 09:24 UTC, nsharma-git commented
Another test run after rebasing to master - https://jenkins.confluent.io/job/cp-ansible-on-demand/124/

2022-04-04 06:02 UTC, utkarsh5474 reviewed
There are some .keytab binary files. Are those intended?

2022-04-04 06:07 UTC, nsharma-git commented
> There are some .keytab binary files. Are those intended?

Thanks! No they ain't. Removed it now.

2022-04-04 06:19 UTC, utkarsh5474 approved these changes
LGTM.

2022-04-07 04:59 UTC, merged